#!/usr/bin/env bash

if [[ "$(uname -s)" == Darwin ]]; then
  echo 'This framework has not been tested on macOS.'
  echo 'To use experimentally, edit this bash script.'
  exit 1
fi

# Dependencies
commands=(
  'docker'
  'docker-compose'
)

for cmd in "${commands[@]}"; do
  if ! command -v "$cmd" >/dev/null; then
    echo "$cmd is either not installed or not on PATH!"
    exit 1
  fi
done

if ! command -v docker-compose >/dev/null; then
  echo 'docker-compose is not installed!'
  exit 1
fi

# set up environment

docker-compose "$@"
